export const blueprintCopy = {
  title: "创作蓝图",
  subtitle: "逐项确认文本规划。全部通过前不会解锁图片、视频、镜头生成或成片制作。",
  planningComplete: "文本规划已完成",
  planningSource: "来自已确认的创意简报与服务端规划 artifact",
  approveSection: "确认此部分",
  approvedSection: "此部分已确认",
  approvingSection: "正在确认",
  requestChanges: "要求修改",
  submitChanges: "提交修改",
  revisingSection: "正在修改",
  feedbackLabel: "修改反馈",
  feedbackPlaceholder: "具体说明需要保留、删除或调整的内容...",
  feedbackRequired: "请先写明希望修改的方向。",
  revisionImpact: "修改后将重新等待确认：",
  finalApprove: "全部确认，进入分镜",
  finalApproving: "正在锁定蓝图",
  finalConfirmTitle: "确认最终蓝图",
  finalConfirm: "确认并进入分镜",
  finalCancel: "继续检查",
  categories: "目录",
  document: "文档",
} as const;
