export const inspirationCopy = {
  title: "灵感对话",
  conversation: "对话",
  brief: "简报",
  you: "你",
  conversationEyebrow: "灵感对话",
  conversationTitle: "先把真正想拍的东西聊清楚",
  conversationNote: "此时只讨论创意，不规划、不生成素材。",
  assistantIntro: "你最想让观众记住这支视频里的什么？先不急着做分镜。",
  composerLabel: "继续补充或调整想法",
  composerPlaceholder: "回答 mise 的问题，或直接说你想调整的方向...",
  send: "发送消息",
  sending: "mise 正在整理你的补充",
  suggestionsLabel: "对话建议",
  briefTitle: "实时创意简报",
  briefSubtitle: "根据对话局部更新",
  documentLabel: "CREATIVE BRIEF",
  emptyValue: "待补充",
  questionsTitle: "仍待回答",
  questionsEmpty: "mise 尚未列出具体问题，你可以继续补充故事、受众或视觉方向。",
  ready: "创意意图已具备规划条件",
  notReady: "回答完待确认问题后即可规划",
  noBrief: "完成对话后可确认创意",
  assurance: "确认前不会规划或生成任何媒体",
  assuranceDetail: "下一步只整理世界观、人物、场景、道具、声音和分镜文本，仍需逐项确认。",
  endFrameControl: "控制成片首尾画面",
  endFrameControlSaving: "正在保存",
  confirm: "确认创意并开始规划",
  confirming: "正在整理创作蓝图",
  submitted: "规划请求已提交，正在等待结果",
  retryPlan: "重试规划",
  planningStatus: "规划状态",
  fields: {
    title: "标题",
    logline: "一句话故事",
    audience: "受众",
    format: "形式",
    duration: "时长",
    aspectRatio: "画幅比例",
    genre: "类型",
    mood: "情绪",
    visualDirection: "视觉方向",
    outline: "故事轮廓",
    mustKeep: "必须保留",
  },
  projectTypeFormats: {
    single_video: "单视频",
    mini_series: "短系列（3-8 集）",
    long_series: "长系列（12-24 集）",
  },
} as const;
